### ISSUE TITLE
NCModelEnricher error

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#194]
Jan-17|17:55:40|ERROR| Failed to process request.
java.lang.IllegalArgumentException: requirement failed: Tokens normalized text: Utah , Texas, generated normalized text: Utah Texas ,
	at scala.Predef$.require(Predef.scala:219) ~[scala-library-2.11.1.jar:?]
	at org.nlpcraft.probe.mgrs.nlp.enrichers.model.NCModelEnricher$$anonfun$org$nlpcraft$probe$mgrs$nlp$enrichers$model$NCModelEnricher$$convert$3$$anonfun$6.apply(NCModelEnricher.scala:316) ~[classes/:?]
	at org.nlpcraft.probe.mgrs.nlp.enrichers.model.NCModelEnricher$$anonfun$org$nlpcraft$probe$mgrs$nlp$enrichers$model$NCModelEnricher$$convert$3$$anonfun$6.apply(NCModelEnricher.scala:302) ~[classes/:?]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.1.jar:?]

Input is : "Utah, Texas"
Nlp2Sql model

**Comment by vic64** [comment]
Looks like it's your code... reassigning.

**Comment by skhdl** [comment]
Seems we have to just delete invalid validation (words order can be changed during collapsing)
Fixed in GH-194
