### ISSUE TITLE
SQL model cannot be started.

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#210]
Generated model IDs are not valid.
(Generator wan't fixed or some wrong validation added)

GH-200

Jan-27|17:46:29|ERROR| Failed to start probe.
org.nlpcraft.common.NCException: Model element ID 'col:territories.territory_description' does not match '^[_a-zA-Z]+[a-zA-Z0-9:-_]*$' regex in: sql.model.id
	at org.nlpcraft.probe.mgrs.deploy.NCDeployManager$$anonfun$start$1$$anonfun$apply$6$$anonfun$apply$7.apply(NCDeployManager.scala:282) ~[classes/:?]
	at org.nlpcraft.probe.mgrs.deploy.NCDeployManager$$anonfun$start$1$$anonfun$apply$6$$anonfun$apply$7.apply(NCDeployManager.scala:280) ~[classes/:?]
	at scala.collection.Iterator$class.foreach(Iterator.scala:743) ~[scala-library-2.11.1.jar:?]

**Comment by skhdl** [comment]
model regenerated.
