### ISSUE TITLE
NCDslTokenPredicate error

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#213]
branch: 200 
model: sql.model.id
request: Utah , Texas

Jan-30|15:25:04|INFO | REST server connection established.
Jan-30|15:25:05|INFO | You are using the latest NLPCraft version.
Jan-30|15:27:49|INFO | Sentences received [txt='Utah , Texas', count=1, usrId=1, mdlId=sql.model.id, srvReqId=g7p96qMdBGC4e4xrAynny]

Jan-30|15:27:49|ERROR| Failed to process request.
java.lang.IllegalArgumentException: Attempt to check unknown element ID 'nlpcraft:num' in: id == 'nlpcraft:num'
	at org.nlpcraft.model.intent.utils.NCDslTokenPredicate.apply(NCDslTokenPredicate.java:345) ~[classes/:?]
	at org.nlpcraft.probe.mgrs.model.NCModelSynonymDslCompiler$FiniteStateMachine$$anon$6.apply(NCModelSynonymDslCompiler.scala:189) ~[classes/:?]
	at org.nlpcraft.probe.mgrs.model.NCModelSynonymDslCompiler$FiniteStateMachine$$anon$6.apply(NCModelSynonymDslCompiler.scala:188) ~[classes/:?]
	at org.nlpcraft.probe.mgrs.model.NCModelSynonymDslCompiler$$anon$1.apply(NCModelSynonymDslCompiler.scala:55) ~[classes/:?]
	at org.nlpcraft.probe.mgrs.model.NCModelSynonymDslCompiler$$anon$1.apply(NCModelSynonymDslCompiler.scala:53) ~[classes/:?]
	at org.nlpcraft.probe.mgrs.NCSynonym$$anonfun$isMatch$4$$anonfun$apply$9.apply(NCSynonym.scala:135) ~[classes/:?]

**Comment by skhdl** [comment]
reproduced after fix GH-213 (I have done local quick fix)

**Comment by vic64** [comment]
Fixed in `release` branch.
