### ISSUE TITLE
NCDslTokenPredicate NPE

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#214]
branch: 200
model: sql.model.id

Jan-30|15:31:32|ERROR| Failed to start probe due to unexpected error.
java.lang.NullPointerException: null
	at org.nlpcraft.model.intent.utils.NCDslTokenPredicate.<init>(NCDslTokenPredicate.java:108) ~[classes/:?]
	at org.nlpcraft.probe.mgrs.model.NCModelSynonymDslCompiler$FiniteStateMachine.exitPredicate(NCModelSynonymDslCompiler.scala:186) ~[classes/:?]
	at org.nlpcraft.probe.mgrs.model.antlr4.NCSynonymDslParser$PredicateContext.exitRule(NCSynonymDslParser.java:348) ~[classes/:?]

**Comment by vic64** [comment]
Fixed in `release` branch.
