### ISSUE TITLE
Tests failed

### ISSUE THREAD

**Issue by skhdl** [nlpcrafters/nlpcraft#241]
+=================================================+

java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:207)
	at org.nlpcraft.probe.mgrs.nlp.NCProbeEnrichmentManager$$anonfun$ask0$6.apply(NCProbeEnrichmentManager.scala:635)
	at org.nlpcraft.probe.mgrs.nlp.NCProbeEnrichmentManager$$anonfun$ask0$6.apply(NCProbeEnrichmentManager.scala:627)
	at org.nlpcraft.common.util.NCUtils$$anonfun$asFuture$2.applyOrElse(NCUtils.scala:951)
	at scala.concurrent.Future$$anonfun$onSuccess$1.apply(Future.scala:117)
	at scala.concurrent.Future$$anonfun$onSuccess$1.apply(Future.scala:115)

How to check - just run HelloWorldTest

**Comment by skhdl** [comment]
`release` branch

**Comment by vic64** [comment]
Fixed in `release`.
